
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "mod"
  name = "coloredslime"
  description = "Dye your slime blocks!"
  version = "1.9.1"
  platform = "fabric"
  license = "MIT"
  source = "https://github.com/FettLol/colored-slime-blocks"
  homepage = "https://github.com/FettLol/colored-slime-blocks"
  author = "Breki Tomasson <breki.tomasson@gmail.com>"

# These are global requirements
[requirements]
  minecraft = ">=1.21.2 <=1.21.3"
  fabricLoader = ">=0.14.25"

[dependencies]
  fabric = "*"

[dev]
  buildCommand = "./gradlew build"
